name: Tests

on:
  push:
  pull_request:
  schedule:
    - cron: '0 6 * * *'

jobs:
  test:
    runs-on: ${{ matrix.os }}

    strategy:
      fail-fast: false
      matrix:
        os:
          # - ubuntu-22.04
          #- windows-2019
          - macos-latest
        rclone:
          - current
          - v1.59.2
          - v1.58.1
          - v1.53.3  # Debian bullseye (current stable)
          - v1.45    # Debian buster (current oldstable)
        exclude:
          # 1.45 - has some odd handling of HOME on OSX - does not use overloaded $HOME
          - os: macos-latest
            rclone: v1.45

    steps:
    - name: Set up environment
      uses: actions/checkout@v1

    - name: Install Python
      uses: actions/setup-python@v4
      with:
        python-version: '>=3.7'

    - name: Install datalad-installer
      run: pip install datalad-installer

    - name: Install git-annex (Ubuntu)
      if: startsWith(matrix.os, 'ubuntu-')
      run: sudo apt install git-annex

    - name: Install git-annex (macOS)
      if: startsWith(matrix.os, 'macos-')
      run: cd $(brew --repo) && ls Library && mkdir -p Library/Formula && wget -O Library/Formula/git-annex.rb https://raw.githubusercontent.com/Homebrew/homebrew-core/6a232aa8b4525cdc102152a6c646572eb09863ed/Formula/git-annex.rb && brew install git-annex

    - name: Install latest rclone
      if: matrix.rclone == 'current'
      run: datalad-installer --sudo ok rclone -m downloads.rclone.org

    - name: Install specific version of rclone
      if: matrix.rclone != 'current'
      run: datalad-installer --sudo ok rclone=${{ matrix.rclone }} -m downloads.rclone.org

    - name: ${{ matrix.module }} tests
      run: |
        PATH=$PWD:$PWD/tests:$PATH all-in-one.sh
        # Test without encryption so we do get 0-sized files in rclone remote store
        PATH=$PWD:$PWD/tests:$PATH GARR_TEST_ENCRYPTION=none all-in-one.sh
